name: melanoma_api
channels:
  - defaults
  - conda-forge
dependencies:
  - uvicorn
  - python-multipart
  - python=3.9
  - fastapi
  - matplotlib
  - tqdm
  - pathlib
  - pip
  - pip:
    - pandas
    - numpy
    - torch
    - torchvision
    - opencv_python
    - fastapi-versioning
