name: melanoma_api
channels:
  - defaults
  - conda-forge
dependencies:
  - uvicorn
  - python=3.9
  - opencv
  - pandas
  - torchvision
  - pytorch
  - fastapi
  - matplotlib
  - albumentations
  - tqdm
  - python-multipart
