version: '3'
services:
  api:
    image: localhost/melanoma_api:latest
    ports:
      - "8081:8081"
    volumes:
      - /home/wilberquito/volumns/api/models:/models:Z
      - /home/wilberquito/volumns/api/api.conf.yml:/app/api.conf.yml:Z
  ui:
    image: localhost/nnui:latest
    ports:
      - "5173:5173"
    volumes:
      - /home/wilberquito/volumns/ui/.env:/app/.env:Z
    depends_on:
      - api
