name: melanoma_nn
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - pip:
    - wandb
    - pandas
    - numpy
    - torch
    - torchvision
    - torchmetrics
    - jupyterlab
    - seaborn
    - mlxtend
    - opencv-python
    - albumentations
