name: melanoma_nn
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - pip:
    - wandb
    - pandas
    - numpy
    - torch==1.11.0
    - torchvision==0.12.0
    - torchmetrics==0.11.4
    - jupyterlab
    - seaborn
    - mlxtend
    - opencv-python
    - albumentations
