name: melanoma_nn
channels:
  - defaults
  - conda-forge
dependencies:
  - python-multipart
  - python=3.9
  - matplotlib
  - tqdm
  - pathlib
  - pip
  - pip:
    - pandas
    - numpy
    - torch
    - torchvision
    - jupyterlab
    - seaborn
